import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '10px',
        sm: '20px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1200px',
        '2xl': '1360px',
      },
    },
    extend: {
      screens: {
        xs: '480px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
      },
      colors: {
        brand: {
          primary: '#72B255',
          primaryHover: '#58A24E',
          soft: '#E6F3D1',
          accent: '#B7D94B',
          gold: '#C7B06B',
        },
        surface: {
          canvas: '#FFFFFF',
          subtle: '#FCFBF8',
          soft: '#F6F4EF',
          elevated: '#FFFFFF',
          brandTint: '#F2F9E8',
          brandSoft: '#E6F3D1',
        },
        text: {
          primary: '#121212',
          secondary: '#4B463F',
          muted: '#9B927F',
          inverse: '#FFFFFF',
          brand: '#58A24E',
        },
        border: {
          soft: '#EFEBE3',
          DEFAULT: '#E3DDD2',
          strong: '#D4CCBE',
          brand: '#CFEBA7',
        },
        status: {
          success: '#2E8B57',
          warning: '#D1A530',
          error: '#C94A4A',
          info: '#3D7EDB',
        },
        neutral: {
          0: '#FFFFFF',
          25: '#FCFBF8',
          50: '#F6F4EF',
          100: '#EFEBE3',
          200: '#E3DDD2',
          300: '#D4CCBE',
          400: '#BFB5A3',
          500: '#9B927F',
          600: '#6F675C',
          700: '#4B463F',
          800: '#2E2B27',
          900: '#171614',
        },
        ink: {
          700: '#2A2A2A',
          800: '#1E1E1E',
          900: '#121212',
        },
      },
      fontFamily: {
        sans: ['Google Sans', 'Inter', 'SF Pro Display', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.025em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-sm': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'section-xl': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'section-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'section-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '30px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        caption: ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      borderRadius: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        pill: '999px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(18,18,18,0.04)',
        sm: '0 4px 12px rgba(18,18,18,0.06)',
        md: '0 12px 24px rgba(18,18,18,0.08)',
        lg: '0 20px 40px rgba(18,18,18,0.10)',
      },
      maxWidth: {
        'container-sm': '640px',
        'container-md': '768px',
        'container-lg': '1024px',
        'container-xl': '1200px',
        'container-2xl': '1360px',
        prose: '72ch',
      },
      zIndex: {
        base: '0',
        dropdown: '20',
        sticky: '30',
        overlay: '40',
        modal: '50',
        toast: '60',
        tooltip: '70',
      },
      opacity: {
        subtle: '0.72',
        soft: '0.88',
        disabled: '0.5',
      },
      transitionDuration: {
        instant: '120ms',
        fast: '180ms',
        base: '240ms',
        slow: '320ms',
        page: '420ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.22, 1, 0.36, 1)',
        soft: 'cubic-bezier(0.16, 1, 0.3, 1)',
        exit: 'cubic-bezier(0.4, 0, 1, 1)',
      },
      keyframes: {
        'fade-up-soft': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-down-soft': {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in-soft': {
          '0%': { opacity: '0', transform: 'translateY(8px) scale(0.985)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'overlay-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'overlay-fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'drawer-right-in': {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'drawer-right-out': {
          '0%': { opacity: '1', transform: 'translateX(0)' },
          '100%': { opacity: '0', transform: 'translateX(24px)' },
        },
      },
      animation: {
        'fade-up-soft': 'fade-up-soft 240ms cubic-bezier(0.22, 1, 0.36, 1)',
        'fade-down-soft': 'fade-down-soft 240ms cubic-bezier(0.22, 1, 0.36, 1)',
        'scale-in-soft': 'scale-in-soft 260ms cubic-bezier(0.16, 1, 0.3, 1)',
        'overlay-fade-in': 'overlay-fade-in 200ms cubic-bezier(0.22, 1, 0.36, 1)',
        'overlay-fade-out': 'overlay-fade-out 160ms cubic-bezier(0.4, 0, 1, 1)',
        'drawer-right-in': 'drawer-right-in 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'drawer-right-out': 'drawer-right-out 200ms cubic-bezier(0.4, 0, 1, 1)',
      },
    },
  },
  plugins: [],
}

export default config
